// Central place for all UI strings (English).
export const t = {
  // App / header
  finTitle: 'KK Financial Assistant',

  // Account bar
  finLocalMode: 'Device-local mode — configure Supabase to enable sync',
  finEmail: 'Email',
  finPassword: 'Password',
  finSignIn: 'Sign in',
  finSignUp: 'Sign up',
  finSignOut: 'Sign out',
  finSignedInAs: 'Signed in as',
  finSignUpDone: 'Account created. Check your inbox if email confirmation is required, then sign in.',

  // Tracker
  finAdd: 'Add',
  finExport: 'Export CSV',
  finAll: 'All',
  finAllStatus: 'All statuses',
  finPaid: 'Paid',
  finUnpaid: 'Unpaid',
  finSearch: 'Search...',
  finEmpty: 'No matching records',
  finNoData: 'No data yet',
  finEarned: 'Total',
  finCollected: 'Collected',
  finOutstanding: 'Outstanding',
  finTypeLecture: 'Lecture',
  finTypeReferral: 'Referred case',
  finTypeHospital: 'Hospital',
  finTypeOther: 'Other',
  finType: 'Type',
  finFieldTitle: 'Title',
  finFieldTitlePh: 'Lecture title or case description',
  finSite: 'Location / hospital',
  finSitePh: 'Location or hospital name',
  finFee: 'Fee',
  finCurrency: 'Currency',
  finDate: 'Date',
  finPatientRef: 'Case reference (optional)',
  finPatientRefPh: 'Reference number or name',
  finNotes: 'Notes',
  finMarkPaid: 'Paid',
  finAddTitle: 'Add record',
  finEditTitle: 'Edit record',
  finEdit: 'Edit',
  finDelete: 'Delete',
  finSave: 'Save',
  finCancel: 'Cancel',
  finConfirmDelete: 'Do you want to delete this record?',
  finTitleRequired: 'Title is required',
  finNoSite: 'No location',
  finAllTime: 'All time',
  finThisMonth: 'This month',
  finLastMonth: 'Last month',
  finThisYear: 'This year',
  finCustom: 'Custom range',
  finFrom: 'From',
  finTo: 'To',
  finSortDateDesc: 'Newest first',
  finSortDateAsc: 'Oldest first',
  finSortFeeDesc: 'Highest fee',
  finSortFeeAsc: 'Lowest fee',
  finStats: 'Show analysis',
  finHideStats: 'Hide analysis',
  finByType: 'By type',
  finBySite: 'By location',
  finLoading: 'Loading…',
  finImport: 'Import',
  finSynced: 'Synced via your account',
  finLocalOnly: 'Saved on this device',
  finRemind: 'Follow-up reminder (optional)',
  finRemindShort: 'Reminder',
  finRemindHint: 'You will get an alert on this date if the payment is still uncollected (requires notifications enabled).',
  finImportEmpty: 'No records found in the file.',
  finImportConfirm: 'Import {n} records?',
  finImportDone: 'Imported {n} records.',
  finImportError: 'Could not read the file. Make sure it is a valid CSV file.',
}
