// Central place for all UI strings (English).
export const t = {
  // App / header
  finTitle: 'KK Financial Assistant',

  // Account bar
  finLocalMode: 'Device-local mode — configure Supabase to enable sync',
  finEmail: 'Email',
  finPassword: 'Password',
  finSignIn: 'Sign in',
  finSignUp: 'Sign up',
  finSignOut: 'Sign out',
  finSignedInAs: 'Signed in as',
  finSignUpDone: 'Account created. Check your email for a confirmation link, then sign in.',
  finErrEmailInvalid: 'Enter a valid email address.',
  finErrPasswordShort: 'Password must be at least 6 characters.',
  finErrAlreadyRegistered: 'This email is already registered — sign in instead.',
  finErrSignupsDisabled: 'Sign-ups are disabled for this project — enable Email signups in Supabase.',
  finErrWrongCredentials: 'Wrong email or password.',
  finErrEmailNotConfirmed:
    "Please confirm your email first (check your inbox), or disable 'Confirm email' in Supabase Auth settings.",

  // Tracker
  finAdd: 'Add',
  finExport: 'Export CSV',
  finAll: 'All',
  finAllStatus: 'All statuses',
  finPaid: 'Paid',
  finUnpaid: 'Unpaid',
  finSearch: 'Search...',
  finEmpty: 'No matching records',
  finNoData: 'No data yet',
  finEarned: 'Total',
  finCollected: 'Collected',
  finOutstanding: 'Outstanding',
  finTypeLecture: 'Lecture',
  finTypeReferral: 'Referred case',
  finTypeHospital: 'Hospital',
  finTypeOther: 'Other',
  finType: 'Type',
  finFieldTitle: 'Title',
  finFieldTitlePh: 'Lecture title or case description',
  finSite: 'Vendor / Hospital',
  finSitePh: 'Vendor or hospital name',
  finSiteNone: '— none —',
  finSiteOther: 'Other (type manually)',
  finSiteFilterAll: 'All vendors',
  finManageVendors: 'Manage the list in Settings',
  finFee: 'Fee',
  finCurrency: 'Currency',
  finDate: 'Date',
  finPatientRef: 'Case reference (optional)',
  finPatientRefPh: 'Reference number or name',
  finNotes: 'Notes',
  finMarkPaid: 'Paid',
  finAddTitle: 'Add record',
  finEditTitle: 'Edit record',
  finEdit: 'Edit',
  finDelete: 'Delete',
  finSave: 'Save',
  finCancel: 'Cancel',
  finConfirmDelete: 'Do you want to delete this record?',
  finTitleRequired: 'Title is required',
  finNoSite: 'No vendor',
  finAllTime: 'All time',
  finThisMonth: 'This month',
  finLastMonth: 'Last month',
  finThisYear: 'This year',
  finCustom: 'Custom range',
  finFrom: 'From',
  finTo: 'To',
  finSortDateDesc: 'Newest first',
  finSortDateAsc: 'Oldest first',
  finSortFeeDesc: 'Highest fee',
  finSortFeeAsc: 'Lowest fee',
  finStats: 'Show analysis',
  finHideStats: 'Hide analysis',
  finByType: 'By type',
  finBySite: 'By vendor / hospital',
  finLoading: 'Loading…',
  finImport: 'Import',
  finSynced: 'Synced via your account',
  finLocalOnly: 'Saved on this device',
  finRemind: 'Follow-up reminder (optional)',
  finRemindShort: 'Reminder',
  finRemindHint: 'You will get an alert on this date if the payment is still uncollected (requires notifications enabled).',
  finImportEmpty: 'No records found in the file.',
  finImportConfirm: 'Import {n} records?',
  finImportDone: 'Imported {n} records.',
  finImportError: 'Could not read the file. Make sure it is a valid CSV file.',

  // Sign-up page
  suTitle: 'Create account',
  suIntro: 'Create an account to sync your ledger across devices. Your records stay private to you.',
  suName: 'Full name',
  suNamePh: 'Your name',
  suPhone: 'Phone number',
  suPhonePh: '+20 1X XXX XXXX',
  suCountry: 'Country',
  suCountrySelect: 'Select your country…',
  suCreate: 'Create account',
  suBack: 'Back',
  suErrName: 'Enter your name.',
  suErrPhone: 'Enter a valid phone number.',
  suErrCountry: 'Select your country.',
  suLocalMode:
    'Accounts are not available in device-local mode — configure Supabase to enable sign-up and sync.',

  // Settings page
  setTitle: 'Settings',
  setVendors: 'Vendors / Hospitals',
  setVendorsHint:
    'Names you add here appear as a dropdown in the record form and as a filter on the main screen.',
  setAddPh: 'New vendor or hospital name',
  setAdd: 'Add',
  setEmptyVendors: 'No vendors yet — add your first one above.',
  setDuplicate: 'This name is already in the list.',
  setDeleteConfirm: 'Remove this vendor from the list? Existing records keep the name.',
  setRenameEntries: 'Also update {n} existing record(s) from "{old}" to "{new}"?',
}
